### ISSUE TITLE
Atone Form: Form is not displayed fully, Background and scrolling bar frame is bad displayed

### ISSUE THREAD

**Issue by at-kiennguyen2** [netprotections/atonecon-android#46]
### Summary (Required)
Form is not displayed fully, Background and scrolling bar frame is bad displayed

### Description (Required)
1. Tap on Atone button to open the Atone form
2. View resource

Actual result: Form is not displayed fully, Background and scrolling bar frame is bad displayed

### Acceptance Criteria (Optional)
Form must be displayed fully, Background and scrolling bar frame is well-displayed

### References (Optional)
Please check file attached below for more details

![sony xperia m4 - resolution 720 x 1280 pixels](https://user-images.githubusercontent.com/24885393/28775574-014babf4-761d-11e7-9824-54accf170381.png)

**Comment by at-duyentran** [comment]
Hello @at-aoiyamamura , @at-diemnguyen 
Below is attached file for display of current Atone Form on a same Android device with this bug.
![current form displayed on android](https://user-images.githubusercontent.com/21256519/30802656-717e84d0-a211-11e7-994d-dae81472ba10.png)

**Comment by at-aoiyamamura** [comment]
@at-hoaiphan @at-duyentran 
According from client, this is no problem now. I will close this issue.
