### ISSUE TITLE
Atone Form: Keyboard should be closed automatic after user inputs wrong Passcode

### ISSUE THREAD

**Issue by at-kiennguyen2** [netprotections/atonecon-android#54]
### Summary (Required)
- After input wrong passcode, Error message will be displayed behind the keyboard and user can't know what are happening. So, i want to suggest to close Keyboard automation after user inputs wrong Passcode

### Description (Required)
1. Go to Passcode screen
2. Input wrong Passcode

Actual result: Error message will be displayed behind the keyboard and user can't know what are happening.

### Acceptance Criteria (Optional)
- Keyboard should be closed automatic after user inputs wrong Passcode.

### References (Optional)
- Please see attached file below for more details:

![keyboard](https://user-images.githubusercontent.com/24885393/29012716-fc771546-7b67-11e7-8d73-6131196a0c07.png)

**Comment by at-duyentran** [comment]
@at-aoiyamamura 
When having new information about this bug, please help to update it

**Comment by at-diemnguyen** [comment]
@at-duyentran Client đã fix bug này rồi.
Thêm xử lý focus out.
Bên mình check lại keyboard đã được focus out chưa và có hiển thị error message chưa nhé.

**Comment by at-duyentran** [comment]
I checked this issue. The function is ok.
