### ISSUE TITLE
Atone Form: There should be a "X" button in the 1st loading screen of Atone Form

### ISSUE THREAD

**Issue by at-kiennguyen2** [netprotections/atonecon-android#56]
### Summary (Required)
https://np-develop.backlog.jp/view/ATONE_APP-170
When user opens Atone Form is-case internet connection weak or can not connect to server. Atone form is loading forever and user can't close this Atone form

A suggestion that there should be a "X" button using to close the Form in the 1st loading screen if there are no requested time out.

### Description (Required)
- Open Atone Form in case internet connection is weak
- Let Atone Form open with White background

Actual result: Atone form is loading forever and user can't close this Atone form

### Acceptance Criteria (Optional)
There should be a "X" button using to close the Form in the 1st loading screen if there are no requested time out.

### References (Optional)
Please check the attached file below for more details:

![missing close button](https://user-images.githubusercontent.com/24885393/29065570-bed30a98-7c56-11e7-96b2-4f1070d01a52.PNG)

**Comment by at-duyentran** [comment]
Close this bug since it related to #47
