### ISSUE TITLE
Atone Form: App is locked rotation after open Atone Form then Close it

### ISSUE THREAD

**Issue by at-kiennguyen2** [netprotections/atonecon-android#63]
### Summary (Required)
App is locked rotation after open Atone Form

### Description (Required)
1. Open App demo
2. Rotate device from Landscape to Portrait and from Portrait to Landscape
3. Open Atone form
4. Close Atone form
5. Try to Rotate to other modes of device

### Acceptance Criteria (Optional)
Rotation from App must work properly again after open Atone Form then close it

**Comment by at-duyentran** [comment]
@at-aoiyamamura 
When having new information about this bug, please help to update it

**Comment by at-aoiyamamura** [comment]
@at-diemnguyen 
Android端末をローテーションしてもフォームの画面表示が崩れないようにクライアント側で修正を行いました。テストをして問題ないか報告お願いします。

**Comment by at-diemnguyen** [comment]
@at-duyentran Bug này client fix rồi, e test lại thử OK chưa rồi report lại nhé

**Comment by at-duyentran** [comment]
@at-aoiyamamura I check this issue on Dev environment, (Deploygate #24). This issue is fixed.
