### ISSUE TITLE
Error callback: Can not trigger SMS_VALIDATION_COUNT

### ISSUE THREAD

**Issue by at-kiennguyen2** [netprotections/atonecon-android#71]
### Summary (Required)
- Can not trigger SMS_VALIDATION_COUNT

### Description (Required)
- Input wrong Passcode many time

**Actual result:** Can not trigger SMS_VALIDATION_COUNT

Error code: EATN0311
Error message: SMS認証に5回以上失敗しました。明日以降に再度お試しください。

### Acceptance Criteria (Optional)
- Please help to know that how can trigger SMS_VALIDATION_COUNT callback?

**Comment by at-duyentran** [comment]
Close this issue since it's not longer used
Refer: https://docs.google.com/spreadsheets/d/1exCwBjRR8_F7cYWvqbtkOgZmP0rFkkEtatGOkBDPCjQ/edit#gid=0
